Payment
bigbangcore/BigBang pull request #412
Opened 2020-03-05 09:31 UTC by shangqd

2020-03-05 09:36 UTC, shangqd commented
# 安全前提条件
# 1 给模板地址转账一次完成指定的金额，不要有多次转账
# 2 height_exec 这个高度过去30个块才开始转账，当然块数越多就越安全

bigluashell exec remove  0 0
bigluashell exec new  0 0 250000000

# 地址
{
    "privkey" : "5d5096994db40b8f6de3cf23108e4cd2d22ce64e574684e4fdd5db831154564e",
    "pubkey" : "5bc0d3b54895e88e83513c23fc692b64cc297fb86736006acc8c9d25b4701b3d",
	17mdq1d15kp6crtg06skvgzs9shj2ptfw4cy530wex2amhdekr1dvg3r2
}
bigbang> makekeypair 
{
    "privkey" : "f327916f28abc92fe351f3d20519eeae23a0fcadd09fa2929f60871f014f364b",
    "pubkey" : "61047649fdb5b6b6cfbfe5bfa5b7b47b711b34994fc8408a7c187095bd332858",
	1b0m37fcne0c7s2j0s17sjd0ve5xv9dx5qzjvzkxppttztjbp0hgy8h9g
}

# 添加电商模板 business:商家地址，customer:客户地址，height_exec:确定矿工的高度（交易失败后奖励给矿工），height_end:结束的高度，amount:交易金额，pledge:保证金
addnewtemplate payment '{"business": "17mdq1d15kp6crtg06skvgzs9shj2ptfw4cy530wex2amhdekr1dvg3r2", "customer":"1b0m37fcne0c7s2j0s17sjd0ve5xv9dx5qzjvzkxppttztjbp0hgy8h9g","height_exec":10,"height_end":80,"amount":100000000,"pledge":20000000}'

# 电商模板地址
2100bzqvp75arxtfqh8c417vr9n453eqjcgbk40qge3r2a6efgyp2ghn5

sendfrom 1965p604xzdrffvg90ax9bk0q3xyqn5zz2vc9zpbe3wdswzazj7d144mm 2100bzqvp75arxtfqh8c417vr9n453eqjcgbk40qge3r2a6efgyp2ghn5 120

# 导入商家
importprivkey 5d5096994db40b8f6de3cf23108e4cd2d22ce64e574684e4fdd5db831154564e 123
unlockkey 5bc0d3b54895e88e83513c23fc692b64cc297fb86736006acc8c9d25b4701b3d 123 0

# 导入客户
importprivkey f327916f28abc92fe351f3d20519eeae23a0fcadd09fa2929f60871f014f364b 123
unlockkey 61047649fdb5b6b6cfbfe5bfa5b7b47b711b34994fc8408a7c187095bd332858 123 0

# 创世块的地址
unlockkey da915f7d9e1b1f6ed99fd816ff977a7d1f17cc95ba0209eef770fb9d00638b49 123 0


# 验证电商模板地址
validateaddress 2100bzqvp75arxtfqh8c417vr9n453eqjcgbk40qge3r2a6efgyp2ghn5

# 给模板地址转账,接受的金额必须等于合同金额（这个主要是用于控制且必须一次完成，如该放开多个输入也合法会产生，相互之间会产生攻击）
sendfrom 1965p604xzdrffvg90ax9bk0q3xyqn5zz2vc9zpbe3wdswzazj7d144mm 2100bzqvp75arxtfqh8c417vr9n453eqjcgbk40qge3r2a6efgyp2ghn5 120

# 违约转账给矿工，120已经包含交易费，如果矿工地址写错了，系统会自动纠正，在块高大于10+30，且小于80 可以转给矿工
sendfrom 2100bzqvp75arxtfqh8c417vr9n453eqjcgbk40qge3r2a6efgyp2ghn5 20m01802pgptaswc5b2dq09kmj10ns88bn69q0msrnz64mtypx4xm5sff 120


# 商家转账
# 100包含交易费用了，块高大于80之后可以操作，小于80转账会失败
sendfrom 21004dh6bc5hwdyf0cyadp2d57y680w4fadbv2fh5djg35n9n0yjaebr4 17mdq1d15kp6crtg06skvgzs9shj2ptfw4cy530wex2amhdekr1dvg3r2 100

# 客户转账
# 100包含交易费用了，块高大于80之后可以操作，小于80转账会失败
sendfrom 21004dh6bc5hwdyf0cyadp2d57y680w4fadbv2fh5djg35n9n0yjaebr4 1b0m37fcne0c7s2j0s17sjd0ve5xv9dx5qzjvzkxppttztjbp0hgy8h9g 20

2020-03-06 03:17 UTC, cchanm commented on src/bigbang/core.cpp
> +            static IBlockChain* pBlockChain = nullptr;
建议：建议在类中添加对像引用，不采用静态变量。

2020-03-06 03:17 UTC, cchanm commented on src/bigbang/core.cpp
> +            pBlockChain->ListDelegatePayment(payment->m_height_exec,block,mapVotes);
问题：该函数未处理失败的情况。

2020-03-06 03:17 UTC, cchanm commented on src/bigbang/core.cpp
> +        auto template_p = CTemplate::CreateTemplatePtr(TEMPLATE_PAYMENT,tx.vchSig);
问题：此处未对变量判断nullptr，如果vchSig值错误，将创建不了对像，即返回null，如果未判断，则会产生错误。

2020-03-06 03:17 UTC, cchanm commented on src/bigbang/core.cpp
> +
问题：在VerifyBlockTx这个函数中未添加该部分的处理，VerifyBlockTx这个函数是BLOCK的交易较验函数，也需要添加处理。

2020-03-06 03:17 UTC, cch809094 commented on src/bigbang/wallet.cpp
> +                uint32 n = dpos.nAgreement.Get32() % mapVotes.size();
建议：建议使用32字节的处理随机数，当前只使用了4字节。

2020-03-06 03:17 UTC, cch809094 commented on src/bigbang/wallet.cpp
> +                    votes.push_back(d.second);
建议：可以不使用votes，直接计算第几位就可以了。

2020-03-06 03:17 UTC, cch809094 commented on src/bigbang/wallet.cpp
> +        }
问题：前面两个IF语句未处理失败的情况，即不满 足条件应签名失败。

2020-03-06 03:17 UTC, cch809094 commented on src/bigbang/wallet.cpp
> +        }
问题：未处理if语句的失败情况。

2020-03-06 03:20 UTC, AlexiaChen requested changes
有个判断条件写重复了，需要改一下可能。

2020-03-06 03:20 UTC, AlexiaChen commented on script/template/rpc.json
> +            },
为什么有两个一模一样的json rpc配置?

2020-03-06 03:20 UTC, AlexiaChen commented on src/common/template/payment.cpp
> +    if (!m_business.IsPubKey() || !m_business.IsPubKey())
这里的判断条件重复了，是不是写错了？是不是m_customer.IsPubKey()?

2020-03-06 04:20 UTC, shangqd commented on script/template/rpc.json
> +            },
一个是请求，一个是应答

2020-03-06 10:21 UTC, shangqd commented on src/common/template/payment.cpp
> +    if (!m_business.IsPubKey() || !m_business.IsPubKey())
更正代码

2020-03-07 04:08 UTC, shangqd commented on src/bigbang/wallet.cpp
> +        }
修改代码

2020-03-07 04:08 UTC, shangqd commented on src/bigbang/wallet.cpp
> +        }
修改代码

2020-03-07 04:32 UTC, shangqd commented on src/bigbang/wallet.cpp
> +                uint32 n = dpos.nAgreement.Get32() % mapVotes.size();
uint256 不支持直接求摸

2020-03-07 04:33 UTC, shangqd commented on src/bigbang/wallet.cpp
> +                    votes.push_back(d.second);
std::multimap<int64, CDestination> 不支持直接访问第n个元素

2020-03-07 04:51 UTC, shangqd commented on src/bigbang/core.cpp
> +            pBlockChain->ListDelegatePayment(payment->m_height_exec,block,mapVotes);
修改代码

2020-03-07 04:58 UTC, shangqd commented on src/bigbang/core.cpp
> +        auto template_p = CTemplate::CreateTemplatePtr(TEMPLATE_PAYMENT,tx.vchSig);
修改代码

2020-03-07 05:02 UTC, shangqd commented on src/bigbang/core.cpp
> +
在VerifyBlockTx 函数中添加检查

2020-03-07 09:15 UTC, shangqd commented on src/bigbang/core.cpp
> +            static IBlockChain* pBlockChain = nullptr;
修改代码

2020-03-07 12:19 UTC, merged