Add recovery from the path of block.dat function
bigbangcore/BigBang pull request #536
Opened 2020-05-15 04:04 UTC by sunhantao

Recovery from block folder to `-datadir` folder. It will purge `-datadir` first except `wallet`
```
Usage: 
bigbang -datadir=/home/user/.bigbang -recoverydir=/home/user/block -debug
```

2020-05-15 07:24 UTC, AlexiaChen requested changes

2020-05-15 07:24 UTC, AlexiaChen commented on src/bigbang/recovery.h
> +// Copyright (c) 2019 The Bigbang developers
CopyRight 改成2019-2020

2020-05-18 06:38 UTC, AlexiaChen approved these changes

2020-05-18 10:13 UTC, cchanm reviewed
测试时发现在导入时，长时间无法终止，因为RPC连接上，只有KILL -9才终止得了，我看purge是在CBbEntry::Initialize处理的，即没有启动模块，建议这个导入像purge一样，在CBbEntry::Initialize中处理，即导入完后再启动。

2020-06-01 09:54 UTC, merged