Fork redeem
bigbangcore/BigBang pull request #565
Opened 2020-06-12 10:08 UTC by sunhantao

2020-06-16 03:05 UTC, cchanm requested changes

2020-06-16 03:05 UTC, cchanm commented on src/storage/blockbase.cpp
> +bool CBlockBase::Initialize(const uint256& hashGenesis, const path& pathDataLocation, bool fDebug, bool fRenewDB)
const uint256& hashGenesis： 这个参数增加后，未被使用。

2020-06-16 03:05 UTC, cchanm commented on src/storage/blockbase.h
> +        return fActive == true;
看看这个函数是不是有问题，函数的内容与函数名不一至，并且调用这个函数的地方也未判断，相当于调用这个函数任何事都未做。同样SetInactive函数也一样。

2020-06-16 03:26 UTC, cchanm requested changes

2020-06-16 03:26 UTC, cchanm commented on src/storage/blockbase.cpp
> +bool CBlockBase::CommitBlockView(CBlockView& view, CBlockIndex* pIndexNew, const CForkSetManager& forkSetMgr)
forkSetMgr这个参数未被使用。

2020-06-16 04:07 UTC, cchanm commented on src/storage/blockbase.cpp
> +}
vAddFork和vRemoveFork没有什么区别，是否这里可以优化一下，只需要在297行处理forkSetMgr.insert(CForkContextEx());

2020-06-18 14:42 UTC, cchanm requested changes

2020-06-18 14:42 UTC, cchanm commented on src/bigbang/core.cpp
> +    {
较验FORK名称和hashParent都存在，forkSetMgr与unconfirmedForkSetMgr重复部分的问题，如果该BLOCK中是短链的，而forkSetMgr是长链的，则forkSetMgr中存在有些名称不应该在短链中存在，但这里被禁用掉了，而hashParent在forkSetMgr中存在，但在短链中不存在，则这里的较验又通过了。
forkSetMgr和unconfirmedForkSetMgr需要整合，去除重复部分的BLOCK后再处理，可以参考UNSPENT的处理方法。

2020-06-18 14:42 UTC, cchanm commented on src/bigbang/core.cpp
> +    if ((destIn.GetTemplateId().GetType() == TEMPLATE_FORK) && (hashFork == GetGenesisBlockHash()))
(hashFork == GetGenesisBlockHash())  这个在VerifyRedeemTx函数较验了，这里重复了，并且这里也应该较验FORK，如果在该IF语句中，则躲过了FORKID的较验。

2020-06-18 14:44 UTC, cchanm requested changes

2020-06-18 14:44 UTC, cchanm commented on src/bigbang/core.cpp
> +    if (forkSetMgr.RetrieveByFork(forkPtr->GetHashFork(), ctxt) || unconfirmedForkSetMgr.RetrieveByFork(forkPtr->GetHashFork(), ctxt))
这里同样存在forkSetMgr和unconfirmedForkSetMgr重复冲突问题。

2020-06-18 15:04 UTC, cchanm requested changes

2020-06-18 15:04 UTC, cchanm commented on src/bigbang/forkmanager.cpp
> +                        Log("fork manager add fork: %s, height: %d", ctxt.hashFork.ToString().c_str(), ctxt.nCreatedHeight);
AddNewForkContext这个函数添加失败了，未做回滚处理，使用得DB中还有失败的FORK数据。

2020-06-18 15:57 UTC, cchanm commented on src/bigbang/txpool.cpp
> +            if (unconfirmedForkSetMgr.RetrieveByTx(it->hashTX, ctxt))
unconfirmedForkSetMgr这个对象的输入值是在那里了，查所有该对象的引用，都未找到数据输入的地方。

2020-06-19 07:55 UTC, cchanm commented on src/bigbang/blockchain.cpp
> +    {
会不会导致同步过来的块是非活跃的FORK，即被回滚的FORK，产生DDOS

2020-06-19 08:16 UTC, cchanm commented on src/bigbang/blockchain.cpp
> +        err = pCoreProtocol->VerifyBlockTx(tx, txContxt, pIndexPrev, nForkHeight, pIndexPrev->GetOriginHash(), forkSetMgr, unconfirmedForkSetMgr);
该BLOCK可能是短链的块，但forkSetMgr这个是长链的数据，所以此处可能存在问题，需要再分析一下。

2020-06-19 08:33 UTC, cchanm requested changes

2020-06-19 08:33 UTC, cchanm commented on src/bigbang/core.cpp
> +
没有对分叉点BLOCK较验，即该创建FORK的TX，要创建的FORK的分叉点BLOCK，可能不在该TX所以在链上，即在其它短链上，所以该TX应该是无效的。

2020-06-19 08:52 UTC, cchanm commented on src/bigbang/core.cpp
> +    return OK;
VerifyForkTx这个函数是较验功能，只对数据读使用，但在这里有写入数据，与这个函数的性质不符，容易产生理解错误，建议把这个添加数据的地方改为较验的上层做，更加明确函数功能。

2020-06-23 09:11 UTC, cchanm commented on src/bigbang/forkmanager.cpp
> +                }
vDeactive.push_back(update.hashFork)这部分是否需要放在 for (const CBlockEx& block : boost::adaptors::reverse(update.vBlockAddNew))之后，如果vBlockAddNew有多个BLOCK，则可能vDeactive.push_back(update.hashFork)被多次调用。

2020-06-29 08:58 UTC, sunhantao commented
由另一个方案替代了#572

2020-06-29 08:58 UTC, closed without merging