Fork rollback and extended maker
bigbangcore/BigBang pull request #584
Opened 2020-07-22 06:49 UTC by cchanm

2020-07-23 02:50 UTC, sunhantao commented on src/bigbang/blockmaker.cpp
> +                        }
修改block.hashPrev的同时，要修改block.nHeight吧？

2020-07-23 03:40 UTC, cchanm commented on src/bigbang/blockmaker.cpp
> +                        }
BLOCK的高度是通过前一块的HASH来计算的，本BLOCK里不需要保储高度值。

2020-07-23 03:57 UTC, AlexiaChen requested changes
give me a feedback please

2020-07-23 03:57 UTC, AlexiaChen commented on src/bigbang/blockchain.cpp
> +    /*if (!CheckContainer())
为什么删除这个？不检查错误了吗？

2020-07-23 03:57 UTC, AlexiaChen commented on src/bigbang/blockchain.cpp
> +    if (!block.IsVacant() || !block.txMint.sendTo.IsNull())
这里是不是&&, 怎么会是||

2020-07-27 04:00 UTC, cchanm commented on src/bigbang/blockchain.cpp
> +    /*if (!CheckContainer())
这里之前测试检查失败，由于新空块的原因，这个功能与checkrepair功能相重，CheckContainer只检查一定深度的块，并且检查的功能不完整，所以我是建议是去掉此功能，如果大家觉得有必要这个功能，可以恢复出来。

2020-07-27 04:53 UTC, cchanm commented on src/bigbang/blockchain.cpp
> +    if (!block.IsVacant() || !block.txMint.sendTo.IsNull())
两种情况需要添加，一、非空块；二、是空块并且txMint.sendTo非空，即是新的空块，以前只要是空块，都不添加，现在增加了新空块，有mint交易，所以这里就添加了，添加后，在RPC上就可以查询到该交易。

2020-07-28 06:18 UTC, AlexiaChen approved these changes

2020-08-03 03:38 UTC, merged