Add New RPC and enhanced it
bigbangcore/BigBang pull request #588
Opened 2020-07-23 03:50 UTC by AlexiaChen

issue #583

2020-07-23 06:14 UTC, cchanm commented on src/bigbang/wallet.cpp
> +            if(tx.nAmount == -1 && nValueIn > tx.nTxFee)
好像不支持-1的值，AmountFromValue这个函数中小于0的会失败

2020-07-23 06:18 UTC, AlexiaChen commented on src/bigbang/wallet.cpp
> +            if(tx.nAmount == -1 && nValueIn > tx.nTxFee)
好的，我看看

2020-07-23 06:23 UTC, cchanm requested changes

2020-07-23 06:23 UTC, cchanm commented on src/bigbang/wallet.cpp
> +                tx.nAmount = nValueIn - tx.nTxFee;
当nAmount 为-1时，SelectCoins可能返回的是0，所以nValueIn这个参数就是0，再调用SelectCoins函数，得到的结果也不正确。

2020-07-24 07:33 UTC, cchanm approved these changes

2020-07-24 07:37 UTC, sunhantao approved these changes

2020-08-03 03:39 UTC, merged